name: Windows
on: [push, pull_request]

jobs:
  buildWindows:
    runs-on: ubuntu-latest
    container:
      image: docker://subsurface/mxe-build-container:2.2

    steps:
    - name: checkout sources
      uses: actions/checkout@v1

    - name: get other dependencies
      env:
         SUBSURFACE_REPO_PATH: ${{ github.workspace }}
      run: |
        echo "Running script to install additional dependancies into container"
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}
        git config --global --add safe.directory ${SUBSURFACE_REPO_PATH}/libdivecomputer
        cd /win
        ln -s /__w/subsurface/subsurface .
        bash -x subsurface/.github/workflows/scripts/windows-container-prep.sh 2>&1 | tee pre-build.log
    - name: run build
      run: |
        cd /win
        bash -x subsurface/.github/workflows/scripts/windows-in-container-build.sh 2>&1 | tee build.log
        grep "Built target installer" build.log

    - name: prepare PR artifacts
      run: |
        mkdir -p Windows-artifacts
        mv ./subsurface-installer.exe ./subsurface.exe ./subsurface.exe.debug Windows-artifacts

    - name: PR artifacts
      uses: actions/upload-artifact@master
      with:
        name: Windows-artifacts
        path: Windows-artifacts
